### ISSUE TITLE
Discussion on dosbox windowresolution= setting

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#37] opened 2020-12-04 13:51 UTC
Ill just copy the wall of text I wrote back in May:

Python 09/05/2020

@eXo I have spent the night balls deep in finding the best resolution to set windowresolution to. Its more complicated than eXoDOS as there are 3 base resolutions we have windows 3.1 set to. I attach screenshots below (if you are interested in having a look yourself) that show how text looks for each win3.1 resolution with dosbox conf windowresolution set to "original" resolution, our standard 1280x960, and windowresolution=desktop (which on my monitor is a weird 1385x1038). I tested many more resolutons than that but they werent worth adding.

- For in windows 3.1 res 640x480 there is no issue with using dosox res 1280x960
- For in windows 3.1 res 800x600 all dosox windowresolutions above 800x600 and upto 1600x1200 look shit with bad text, even PixelPerfect leaves it at 800x600 for my 1080 monitor
- For in windows 3.1 res 1024x768 same as above, no dosbox res inside the range of a 1080 monitor looks good and again PP leaves it at 1024x768

What we do with this info depends on how we approach the related issue of High Colour games. I will leave my recommendations to that linked issue: #59 

![win3xUpscalingWindowRes](https://user-images.githubusercontent.com/67406191/101171242-9900f000-3693-11eb-9e25-b1dc632eac79.png)

**Comment by exoscoriae** [comment] 2021-02-02 22:20
shit. we need the recap of what we discussed in the server posted in here.
======================================================


**Small**

DOS
windowresolution=1280x960 goes to windowresolution=640x480

WIN 3.1
windowresolution=640x480 goes to windowresolution=640x480
windowresolution=800x600 goes to windowresolution=800x600
windowresolution=1024x768 goes to windowresolution=1024x768


**Medium**

DOS
windowresolution=1280x960 goes to windowresolution=1280x960

WIN 3.1
windowresolution=640x480 goes to windowresolution=1280x960
windowresolution=800x600 goes to windowresolution=800x600
windowresolution=1024x768 goes to windowresolution=1024x768


**Large**

DOS
windowresolution=1280x960 goes to windowresolution=2560x1920

WIN 3.1
windowresolution=640x480 goes to windowresolution=2560x1920
windowresolution=800x600 goes to windowresolution=2400x1800
windowresolution=1024x768 goes to windowresolution=2048x1536

**Comment by exoscoriae** [comment] 2021-02-02 22:21
so, to enact this, we need to first set each game to it's native resolution. Did we discuss an easy way to accomplish this?

**Comment by Python-Exoproject** [comment] 2021-02-03 11:48
This was left for information as it forms part of the greater resolution\scaler issues which are now issue #59. The spreadsheet in the last comment of that issue lists all the changes needed at the time I posted it. But good to put that info here as its the most relevant issue for it.

The spreadsheet I posted has three tabs, the first of which lists the games that need to be changed to windowresolution=1024x768 and 800x600. Every other game needs to be windowresolution=640x480. I guess we can search and replace for all of the following and set them to windowresolution=640x480:

windowresolution=1280x960
windowresolution=original
windowresolution    = 1280x960
windowresolution    = original

Then manually switch the smaller number of 1024 and 800 games from the spreadsheet? That should cover everything

**Comment by exoscoriae** [comment] 2021-02-03 21:21
@Python-Exoproject 
two window settings for medium and small are identical. That seems off.

I'm not entirely sure why 800x600 has to stay that for medium window settings?
Can it not simply double to 1600x1200? I suppose the height exceeds 1080, which is why we chose not to go with that?

I used a resolution scale calculator (https://bneijt.nl/pr/resolution-scale-calculator/)

It suggested 1280x960. This won't result in half pixels according to it. Does that work for you?

**Comment by exoscoriae** [comment] 2021-02-03 21:29
also, a thought. Previously the setup file could revert between small and large easily. change value A to value B or value B to value A. right?

This is a bit more convoluted now. Going between small and large is fairly easy, as large values are unique. So, if a user chooses large resolution and then changes their mind and goes to small. Small basically just resets large to the native values in the conf file.

I think the problem is when medium gets involved. 1024 in medium is ok, because that isn't being modified. So, we can treat that the same as small.

The main issue is if we use my suggestion above and allow medium to be 1280x960. This is the same size the 640x480 window is scaling to. So if we do that, they sort of get merged, and you can go back to small again because it won't know what size it used to be. 

maybe I'm overthinking this.

I do think 800x600 is a bit dinky for a medium a 1080p window... but who knows.... thoughts?

**Comment by exoscoriae** [comment] 2021-02-03 21:31
gah. we also need to decide how to handle full screen vs window in the install.bat

right now it is full or window. no resolution size is offered. I think I may be inclined to keep it that way. Seems like a massive headache trying to incorporate this on a game by game basis.

**Comment by exoscoriae** [comment] 2021-02-03 21:32
moving this to QA for discussion.

**Comment by Python-Exoproject** [comment] 2021-02-04 06:56
Yeah, the reason Small and Medium are the same for 800x600 and 1024x768 is that they cant scale properly due to as you pointed out, double 800x600 is 1600x1200 which is beyond a 1080 res. To see the results of 800x600 scaling to 1280x960 just look at the picture I attached to my first post, it makes the fonts look hideous. If there was a suitable res between 800x600 and 1920x1080 then pixel perfect would use it, however it keeps it at 800x600 for the same reasons - it just doesnt scale well without straight up doubling\tripling\etc. I agree though, it looks dinky. But id rather dinky and clear than bigger and hard to read. Its not too terrible on 1080, just not great - and there is always fullscreen

Your second point is not an issue if my point above is granted. If you still feel that 800x600 should go to 1280x960 for 1080 res then yes this is an issue.

I dont think we should get into the install.bat, it should remain just as a choice between windowed or fullscreen

**Comment by Python-Exoproject** [comment] 2021-02-06 15:12
Moving it back to main que in to continue discussion in case its been missed here

**Comment by exoscoriae** [comment] 2021-02-07 04:30
ok. sounds good. setup file is set to the above.

**Comment by Python-Exoproject** [comment] 2021-02-07 10:11
Looked at the new "Setup eXoWin3x.bat" file. I think it needs a couple more lines as per below:

To cover a user changing from medium to small we need under :small 
if exist .\%%a\dosbox.conf ssr 0 windowresolution=1280x960 windowresolution=640x480 ".\%%a\dosbox.conf"
if exist .\%%a\dosbox2.conf ssr 0 windowresolution=1280x960 windowresolution=640x480 ".\%%a\dosbox2.conf"

To cover a user changing from large to medium we need under :medium
if exist .\%%a\dosbox.conf ssr 0 windowresolution=2560x1920 windowresolution=1280x960 ".\%%a\dosbox.conf" 
if exist .\%%a\dosbox.conf ssr 0 windowresolution=2400x1800 windowresolution=800x600 ".\%%a\dosbox.conf" 
if exist .\%%a\dosbox.conf ssr 0 windowresolution=2048x1536 windowresolution=1024x768 ".\%%a\dosbox.conf" 
if exist .\%%a\dosbox2.conf ssr 0 windowresolution=2560x1920 windowresolution=1280x960 ".\%%a\dosbox2.conf" 
if exist .\%%a\dosbox2.conf ssr 0 windowresolution=2400x1800 windowresolution=800x600 ".\%%a\dosbox2.conf" 
if exist .\%%a\dosbox2.conf ssr 0 windowresolution=2048x1536 windowresolution=1024x768 ".\%%a\dosbox2.conf"

To cover a user changing from medium to large we need under :large
if exist .\%%a\dosbox.conf ssr 0 windowresolution=1280x960 windowresolution=2560x1920 ".\%%a\dosbox.conf"
if exist .\%%a\dosbox2.conf ssr 0 windowresolution=1280x960 windowresolution=2560x1920 ".\%%a\dosbox2.conf"

**Comment by Python-Exoproject** [comment] 2021-02-07 10:14
Another thing I noticed is that if a user selects fullscreen instead of winodw they miss the opportunity to set window resolution therefore when they install an individual game and choose "window" it will be in the native res of 640x480 which would suck for those 4k people. 

We probably need to separate the choice of window\fullscreen in setup from the settings for resolution. I.E. first question, "What is your primary monitors resolution (4k, 1080, <1080)?" and after that choice and changes, "Would you like Fullscreen or Window as default setting?"

**Comment by exoscoriae** [comment] 2021-02-08 17:58
changes made.

I will be testing the setup file today and tomorrow.

**Closed as completed by exoscoriae** 2021-02-08 17:58 UTC
Labels: bug
